// Copyright (C) 2026 Toit contributors.
// AUTO-GENERATED by tools/gen_plat_jt.py — do not edit by hand.
//
// Per-symbol wrapper stubs + the jump-table data. Each stub is a
// 16-byte Thumb-2 sequence: load `g_plat_jt[slot]`, tail-call. The
// ABI args (r0-r3 + stack) are already in place by the time the BL
// from the caller lands, so a bare `bx` to the real function preserves
// every argument and return convention.

#include "plat_jt.h"

extern void *__real_BSP_QSPI_Erase_Safe;
extern void *__real_BSP_QSPI_Read_Safe;
extern void *__real_BSP_QSPI_Write_Safe;
extern void *__real_BSP_SetPlatConfigItemValue;
extern void *__real_GPIO_Config;
extern void *__real_GPIO_IomuxEC618;
extern void *__real_GPIO_Output;
extern void *__real_GPIO_PullConfig;
extern void *__real_GPIO_clearInterruptFlags;
extern void *__real_GPIO_getInterruptFlags;
extern void *__real_GPIO_interruptConfig;
extern void *__real_GPIO_pinConfig;
extern void *__real_GPIO_pinRead;
extern void *__real_GPIO_pinWrite;
extern void *__real_OsaSystemTimeReadRamUtc;
extern void *__real_OsaTimerSync;
extern void *__real_ResetStateGet;
extern void *__real_Uart_BaseInitEx;
extern void *__real_Uart_ChangeBR;
extern void *__real_Uart_DeInit;
extern void *__real_Uart_IsTSREmpty;
extern void *__real_Uart_RxBufferClear;
extern void *__real_Uart_RxBufferRead;
extern void *__real_Uart_TxTaskSafe;
extern void *__real_XIC_EnableIRQ;
extern void *__real_XIC_SetVector;
extern void *__real__ZNSt13random_device7_M_finiEv;
extern void *__real__ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE;
extern void *__real__ZNSt13random_device9_M_getvalEv;
extern void *__real__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv;
extern void *__real__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_;
extern void *__real__ZSt25__throw_bad_function_callv;
extern void *__real__ZdaPv;
extern void *__real__ZdlPv;
extern void *__real___adddf3;
extern void *__real___aeabi_atexit;
extern void *__real___aeabi_d2f;
extern void *__real___aeabi_d2iz;
extern void *__real___aeabi_d2lz;
extern void *__real___aeabi_dcmpeq;
extern void *__real___aeabi_dcmpge;
extern void *__real___aeabi_dcmpgt;
extern void *__real___aeabi_dcmple;
extern void *__real___aeabi_dcmplt;
extern void *__real___aeabi_dcmpun;
extern void *__real___aeabi_ddiv;
extern void *__real___aeabi_dmul;
extern void *__real___aeabi_dsub;
extern void *__real___aeabi_f2d;
extern void *__real___aeabi_i2d;
extern void *__real___aeabi_l2d;
extern void *__real___aeabi_ldivmod;
extern void *__real___aeabi_uldivmod;
extern void *__real___assert_func;
extern void *__real___cxa_thread_atexit;
extern void *__real___emutls_get_address;
extern void *__real___popcountdi2;
extern void *__real___popcountsi2;
extern void *__real___wrap_time;
extern void *__real_abort;
extern void *__real_acos;
extern void *__real_aligned_alloc;
extern void *__real_apmuSetDeepestSleepMode;
extern void *__real_appGetECBCInfoSync;
extern void *__real_appSetCFUN;
extern void *__real_asin;
extern void *__real_atan;
extern void *__real_atan2;
extern void *__real_calloc;
extern void *__real_ceil;
extern void *__real_cos;
extern void *__real_cosh;
extern void *__real_deregisterPSEventCallback;
extern void *__real_exp;
extern void *__real_fflush;
extern void *__real_floor;
extern void *__real_fmod;
extern void *__real_fputc;
extern void *__real_fputs;
extern void *__real_free;
extern void *__real_fwrite;
extern void *__real_gmtime_r;
extern void *__real_iprintf;
extern void *__real_isspace;
extern void *__real_localtime_r;
extern void *__real_log;
extern void *__real_malloc;
extern void *__real_memchr;
extern void *__real_memcmp;
extern void *__real_memcpy;
extern void *__real_memmove;
extern void *__real_memset;
extern void *__real_mktime;
extern void *__real_osDelay;
extern void *__real_osKernelGetTickCount;
extern void *__real_pbuf_alloc;
extern void *__real_pbuf_cat;
extern void *__real_pbuf_free;
extern void *__real_pbuf_ref;
extern void *__real_pow;
extern void *__real_psSetCdgcont;
extern void *__real_putenv;
extern void *__real_puts;
extern void *__real_realloc;
extern void *__real_registerPSEventCallback;
extern void *__real_rngGenRandom;
extern void *__real_round;
extern void *__real_sin;
extern void *__real_sinh;
extern void *__real_siprintf;
extern void *__real_slpManApplyPlatVoteHandle;
extern void *__real_slpManDeepSlpTimerRegisterExpCb;
extern void *__real_slpManDeepSlpTimerStart;
extern void *__real_slpManPlatVoteDisableSleep;
extern void *__real_slpManPlatVoteEnableSleep;
extern void *__real_slpManSetPmuSleepMode;
extern void *__real_sniprintf;
extern void *__real_soc_power_mode;
extern void *__real_sqrt;
extern void *__real_strchr;
extern void *__real_strcmp;
extern void *__real_strcpy;
extern void *__real_strlen;
extern void *__real_strncmp;
extern void *__real_strncpy;
extern void *__real_strstr;
extern void *__real_strtod;
extern void *__real_tan;
extern void *__real_tanh;
extern void *__real_tcp_accept;
extern void *__real_tcp_arg;
extern void *__real_tcp_bind;
extern void *__real_tcp_close;
extern void *__real_tcp_connect;
extern void *__real_tcp_err;
extern void *__real_tcp_listen_with_backlog;
extern void *__real_tcp_new;
extern void *__real_tcp_output;
extern void *__real_tcp_recv;
extern void *__real_tcp_recved;
extern void *__real_tcp_sent;
extern void *__real_tcp_shutdown;
extern void *__real_tcp_write;
extern void *__real_tcpip_callback_with_block;
extern void *__real_trunc;
extern void *__real_tzset;
extern void *__real_udp_bind;
extern void *__real_udp_connect;
extern void *__real_udp_new;
extern void *__real_udp_recv;
extern void *__real_udp_remove;
extern void *__real_udp_send;
extern void *__real_udp_sendto;
extern void *__real_vPortGetHeapStats;
extern void *__real_vPortGetHeapTag;
extern void *__real_vPortIterateAllocations;
extern void *__real_vPortSetHeapTag;
extern void *__real_vQueueDelete;
extern void *__real_vTaskDelete;
extern void *__real_vfiprintf;
extern void *__real_xQueueCreateMutex;
extern void *__real_xQueueGenericCreate;
extern void *__real_xQueueGenericReceive;
extern void *__real_xQueueGenericSend;
extern void *__real_xQueueGenericSendFromISR;
extern void *__real_xQueueGetMutexHolder;
extern void *__real_xTaskCreate;
extern void *__real_xTaskGetCurrentTaskHandle;
extern void *__real_xTaskNotifyWait;

// Placed at a fixed flash address (see ec618_0h00_flash.c, .jt_data
// section) so dual-linked VM slots resolve to the same g_plat_jt[]
// regardless of which slot's image they were linked from.
__attribute__((section(".jt_data"), used))
void *const g_plat_jt[PLAT_JT_COUNT] = {
    [PLAT_JT_BSP_QSPI_Erase_Safe] = &__real_BSP_QSPI_Erase_Safe,
    [PLAT_JT_BSP_QSPI_Read_Safe] = &__real_BSP_QSPI_Read_Safe,
    [PLAT_JT_BSP_QSPI_Write_Safe] = &__real_BSP_QSPI_Write_Safe,
    [PLAT_JT_BSP_SetPlatConfigItemValue] = &__real_BSP_SetPlatConfigItemValue,
    [PLAT_JT_GPIO_Config] = &__real_GPIO_Config,
    [PLAT_JT_GPIO_IomuxEC618] = &__real_GPIO_IomuxEC618,
    [PLAT_JT_GPIO_Output] = &__real_GPIO_Output,
    [PLAT_JT_GPIO_PullConfig] = &__real_GPIO_PullConfig,
    [PLAT_JT_GPIO_clearInterruptFlags] = &__real_GPIO_clearInterruptFlags,
    [PLAT_JT_GPIO_getInterruptFlags] = &__real_GPIO_getInterruptFlags,
    [PLAT_JT_GPIO_interruptConfig] = &__real_GPIO_interruptConfig,
    [PLAT_JT_GPIO_pinConfig] = &__real_GPIO_pinConfig,
    [PLAT_JT_GPIO_pinRead] = &__real_GPIO_pinRead,
    [PLAT_JT_GPIO_pinWrite] = &__real_GPIO_pinWrite,
    [PLAT_JT_OsaSystemTimeReadRamUtc] = &__real_OsaSystemTimeReadRamUtc,
    [PLAT_JT_OsaTimerSync] = &__real_OsaTimerSync,
    [PLAT_JT_ResetStateGet] = &__real_ResetStateGet,
    [PLAT_JT_Uart_BaseInitEx] = &__real_Uart_BaseInitEx,
    [PLAT_JT_Uart_ChangeBR] = &__real_Uart_ChangeBR,
    [PLAT_JT_Uart_DeInit] = &__real_Uart_DeInit,
    [PLAT_JT_Uart_IsTSREmpty] = &__real_Uart_IsTSREmpty,
    [PLAT_JT_Uart_RxBufferClear] = &__real_Uart_RxBufferClear,
    [PLAT_JT_Uart_RxBufferRead] = &__real_Uart_RxBufferRead,
    [PLAT_JT_Uart_TxTaskSafe] = &__real_Uart_TxTaskSafe,
    [PLAT_JT_XIC_EnableIRQ] = &__real_XIC_EnableIRQ,
    [PLAT_JT_XIC_SetVector] = &__real_XIC_SetVector,
    [PLAT_JT__ZNSt13random_device7_M_finiEv] = &__real__ZNSt13random_device7_M_finiEv,
    [PLAT_JT__ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE] = &__real__ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE,
    [PLAT_JT__ZNSt13random_device9_M_getvalEv] = &__real__ZNSt13random_device9_M_getvalEv,
    [PLAT_JT__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv] = &__real__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv,
    [PLAT_JT__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_] = &__real__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_,
    [PLAT_JT__ZSt25__throw_bad_function_callv] = &__real__ZSt25__throw_bad_function_callv,
    [PLAT_JT__ZdaPv] = &__real__ZdaPv,
    [PLAT_JT__ZdlPv] = &__real__ZdlPv,
    [PLAT_JT___adddf3] = &__real___adddf3,
    [PLAT_JT___aeabi_atexit] = &__real___aeabi_atexit,
    [PLAT_JT___aeabi_d2f] = &__real___aeabi_d2f,
    [PLAT_JT___aeabi_d2iz] = &__real___aeabi_d2iz,
    [PLAT_JT___aeabi_d2lz] = &__real___aeabi_d2lz,
    [PLAT_JT___aeabi_dcmpeq] = &__real___aeabi_dcmpeq,
    [PLAT_JT___aeabi_dcmpge] = &__real___aeabi_dcmpge,
    [PLAT_JT___aeabi_dcmpgt] = &__real___aeabi_dcmpgt,
    [PLAT_JT___aeabi_dcmple] = &__real___aeabi_dcmple,
    [PLAT_JT___aeabi_dcmplt] = &__real___aeabi_dcmplt,
    [PLAT_JT___aeabi_dcmpun] = &__real___aeabi_dcmpun,
    [PLAT_JT___aeabi_ddiv] = &__real___aeabi_ddiv,
    [PLAT_JT___aeabi_dmul] = &__real___aeabi_dmul,
    [PLAT_JT___aeabi_dsub] = &__real___aeabi_dsub,
    [PLAT_JT___aeabi_f2d] = &__real___aeabi_f2d,
    [PLAT_JT___aeabi_i2d] = &__real___aeabi_i2d,
    [PLAT_JT___aeabi_l2d] = &__real___aeabi_l2d,
    [PLAT_JT___aeabi_ldivmod] = &__real___aeabi_ldivmod,
    [PLAT_JT___aeabi_uldivmod] = &__real___aeabi_uldivmod,
    [PLAT_JT___assert_func] = &__real___assert_func,
    [PLAT_JT___cxa_thread_atexit] = &__real___cxa_thread_atexit,
    [PLAT_JT___emutls_get_address] = &__real___emutls_get_address,
    [PLAT_JT___popcountdi2] = &__real___popcountdi2,
    [PLAT_JT___popcountsi2] = &__real___popcountsi2,
    [PLAT_JT___wrap_time] = &__real___wrap_time,
    [PLAT_JT_abort] = &__real_abort,
    [PLAT_JT_acos] = &__real_acos,
    [PLAT_JT_aligned_alloc] = &__real_aligned_alloc,
    [PLAT_JT_apmuSetDeepestSleepMode] = &__real_apmuSetDeepestSleepMode,
    [PLAT_JT_appGetECBCInfoSync] = &__real_appGetECBCInfoSync,
    [PLAT_JT_appSetCFUN] = &__real_appSetCFUN,
    [PLAT_JT_asin] = &__real_asin,
    [PLAT_JT_atan] = &__real_atan,
    [PLAT_JT_atan2] = &__real_atan2,
    [PLAT_JT_calloc] = &__real_calloc,
    [PLAT_JT_ceil] = &__real_ceil,
    [PLAT_JT_cos] = &__real_cos,
    [PLAT_JT_cosh] = &__real_cosh,
    [PLAT_JT_deregisterPSEventCallback] = &__real_deregisterPSEventCallback,
    [PLAT_JT_exp] = &__real_exp,
    [PLAT_JT_fflush] = &__real_fflush,
    [PLAT_JT_floor] = &__real_floor,
    [PLAT_JT_fmod] = &__real_fmod,
    [PLAT_JT_fputc] = &__real_fputc,
    [PLAT_JT_fputs] = &__real_fputs,
    [PLAT_JT_free] = &__real_free,
    [PLAT_JT_fwrite] = &__real_fwrite,
    [PLAT_JT_gmtime_r] = &__real_gmtime_r,
    [PLAT_JT_iprintf] = &__real_iprintf,
    [PLAT_JT_isspace] = &__real_isspace,
    [PLAT_JT_localtime_r] = &__real_localtime_r,
    [PLAT_JT_log] = &__real_log,
    [PLAT_JT_malloc] = &__real_malloc,
    [PLAT_JT_memchr] = &__real_memchr,
    [PLAT_JT_memcmp] = &__real_memcmp,
    [PLAT_JT_memcpy] = &__real_memcpy,
    [PLAT_JT_memmove] = &__real_memmove,
    [PLAT_JT_memset] = &__real_memset,
    [PLAT_JT_mktime] = &__real_mktime,
    [PLAT_JT_osDelay] = &__real_osDelay,
    [PLAT_JT_osKernelGetTickCount] = &__real_osKernelGetTickCount,
    [PLAT_JT_pbuf_alloc] = &__real_pbuf_alloc,
    [PLAT_JT_pbuf_cat] = &__real_pbuf_cat,
    [PLAT_JT_pbuf_free] = &__real_pbuf_free,
    [PLAT_JT_pbuf_ref] = &__real_pbuf_ref,
    [PLAT_JT_pow] = &__real_pow,
    [PLAT_JT_psSetCdgcont] = &__real_psSetCdgcont,
    [PLAT_JT_putenv] = &__real_putenv,
    [PLAT_JT_puts] = &__real_puts,
    [PLAT_JT_realloc] = &__real_realloc,
    [PLAT_JT_registerPSEventCallback] = &__real_registerPSEventCallback,
    [PLAT_JT_rngGenRandom] = &__real_rngGenRandom,
    [PLAT_JT_round] = &__real_round,
    [PLAT_JT_sin] = &__real_sin,
    [PLAT_JT_sinh] = &__real_sinh,
    [PLAT_JT_siprintf] = &__real_siprintf,
    [PLAT_JT_slpManApplyPlatVoteHandle] = &__real_slpManApplyPlatVoteHandle,
    [PLAT_JT_slpManDeepSlpTimerRegisterExpCb] = &__real_slpManDeepSlpTimerRegisterExpCb,
    [PLAT_JT_slpManDeepSlpTimerStart] = &__real_slpManDeepSlpTimerStart,
    [PLAT_JT_slpManPlatVoteDisableSleep] = &__real_slpManPlatVoteDisableSleep,
    [PLAT_JT_slpManPlatVoteEnableSleep] = &__real_slpManPlatVoteEnableSleep,
    [PLAT_JT_slpManSetPmuSleepMode] = &__real_slpManSetPmuSleepMode,
    [PLAT_JT_sniprintf] = &__real_sniprintf,
    [PLAT_JT_soc_power_mode] = &__real_soc_power_mode,
    [PLAT_JT_sqrt] = &__real_sqrt,
    [PLAT_JT_strchr] = &__real_strchr,
    [PLAT_JT_strcmp] = &__real_strcmp,
    [PLAT_JT_strcpy] = &__real_strcpy,
    [PLAT_JT_strlen] = &__real_strlen,
    [PLAT_JT_strncmp] = &__real_strncmp,
    [PLAT_JT_strncpy] = &__real_strncpy,
    [PLAT_JT_strstr] = &__real_strstr,
    [PLAT_JT_strtod] = &__real_strtod,
    [PLAT_JT_tan] = &__real_tan,
    [PLAT_JT_tanh] = &__real_tanh,
    [PLAT_JT_tcp_accept] = &__real_tcp_accept,
    [PLAT_JT_tcp_arg] = &__real_tcp_arg,
    [PLAT_JT_tcp_bind] = &__real_tcp_bind,
    [PLAT_JT_tcp_close] = &__real_tcp_close,
    [PLAT_JT_tcp_connect] = &__real_tcp_connect,
    [PLAT_JT_tcp_err] = &__real_tcp_err,
    [PLAT_JT_tcp_listen_with_backlog] = &__real_tcp_listen_with_backlog,
    [PLAT_JT_tcp_new] = &__real_tcp_new,
    [PLAT_JT_tcp_output] = &__real_tcp_output,
    [PLAT_JT_tcp_recv] = &__real_tcp_recv,
    [PLAT_JT_tcp_recved] = &__real_tcp_recved,
    [PLAT_JT_tcp_sent] = &__real_tcp_sent,
    [PLAT_JT_tcp_shutdown] = &__real_tcp_shutdown,
    [PLAT_JT_tcp_write] = &__real_tcp_write,
    [PLAT_JT_tcpip_callback_with_block] = &__real_tcpip_callback_with_block,
    [PLAT_JT_trunc] = &__real_trunc,
    [PLAT_JT_tzset] = &__real_tzset,
    [PLAT_JT_udp_bind] = &__real_udp_bind,
    [PLAT_JT_udp_connect] = &__real_udp_connect,
    [PLAT_JT_udp_new] = &__real_udp_new,
    [PLAT_JT_udp_recv] = &__real_udp_recv,
    [PLAT_JT_udp_remove] = &__real_udp_remove,
    [PLAT_JT_udp_send] = &__real_udp_send,
    [PLAT_JT_udp_sendto] = &__real_udp_sendto,
    [PLAT_JT_vPortGetHeapStats] = &__real_vPortGetHeapStats,
    [PLAT_JT_vPortGetHeapTag] = &__real_vPortGetHeapTag,
    [PLAT_JT_vPortIterateAllocations] = &__real_vPortIterateAllocations,
    [PLAT_JT_vPortSetHeapTag] = &__real_vPortSetHeapTag,
    [PLAT_JT_vQueueDelete] = &__real_vQueueDelete,
    [PLAT_JT_vTaskDelete] = &__real_vTaskDelete,
    [PLAT_JT_vfiprintf] = &__real_vfiprintf,
    [PLAT_JT_xQueueCreateMutex] = &__real_xQueueCreateMutex,
    [PLAT_JT_xQueueGenericCreate] = &__real_xQueueGenericCreate,
    [PLAT_JT_xQueueGenericReceive] = &__real_xQueueGenericReceive,
    [PLAT_JT_xQueueGenericSend] = &__real_xQueueGenericSend,
    [PLAT_JT_xQueueGenericSendFromISR] = &__real_xQueueGenericSendFromISR,
    [PLAT_JT_xQueueGetMutexHolder] = &__real_xQueueGetMutexHolder,
    [PLAT_JT_xTaskCreate] = &__real_xTaskCreate,
    [PLAT_JT_xTaskGetCurrentTaskHandle] = &__real_xTaskGetCurrentTaskHandle,
    [PLAT_JT_xTaskNotifyWait] = &__real_xTaskNotifyWait,
};

#define PLAT_STUB(name, slot)                                       \
    __attribute__((naked, noinline))                                 \
    void __wrap_##name(void) {                                      \
        __asm__ volatile (                                           \
            "movw r12, #:lower16:g_plat_jt + " #slot " * 4 \n"      \
            "movt r12, #:upper16:g_plat_jt + " #slot " * 4 \n"      \
            "ldr  r12, [r12]                              \n"       \
            "bx   r12                                     \n"       \
        );                                                           \
    }

PLAT_STUB(BSP_QSPI_Erase_Safe, 0)
PLAT_STUB(BSP_QSPI_Read_Safe, 1)
PLAT_STUB(BSP_QSPI_Write_Safe, 2)
PLAT_STUB(BSP_SetPlatConfigItemValue, 3)
PLAT_STUB(GPIO_Config, 4)
PLAT_STUB(GPIO_IomuxEC618, 5)
PLAT_STUB(GPIO_Output, 6)
PLAT_STUB(GPIO_PullConfig, 7)
PLAT_STUB(GPIO_clearInterruptFlags, 8)
PLAT_STUB(GPIO_getInterruptFlags, 9)
PLAT_STUB(GPIO_interruptConfig, 10)
PLAT_STUB(GPIO_pinConfig, 11)
PLAT_STUB(GPIO_pinRead, 12)
PLAT_STUB(GPIO_pinWrite, 13)
PLAT_STUB(OsaSystemTimeReadRamUtc, 14)
PLAT_STUB(OsaTimerSync, 15)
PLAT_STUB(ResetStateGet, 16)
PLAT_STUB(Uart_BaseInitEx, 17)
PLAT_STUB(Uart_ChangeBR, 18)
PLAT_STUB(Uart_DeInit, 19)
PLAT_STUB(Uart_IsTSREmpty, 20)
PLAT_STUB(Uart_RxBufferClear, 21)
PLAT_STUB(Uart_RxBufferRead, 22)
PLAT_STUB(Uart_TxTaskSafe, 23)
PLAT_STUB(XIC_EnableIRQ, 24)
PLAT_STUB(XIC_SetVector, 25)
PLAT_STUB(_ZNSt13random_device7_M_finiEv, 26)
PLAT_STUB(_ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE, 27)
PLAT_STUB(_ZNSt13random_device9_M_getvalEv, 28)
PLAT_STUB(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv, 29)
PLAT_STUB(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_, 30)
PLAT_STUB(_ZSt25__throw_bad_function_callv, 31)
PLAT_STUB(_ZdaPv, 32)
PLAT_STUB(_ZdlPv, 33)
PLAT_STUB(__adddf3, 34)
PLAT_STUB(__aeabi_atexit, 35)
PLAT_STUB(__aeabi_d2f, 36)
PLAT_STUB(__aeabi_d2iz, 37)
PLAT_STUB(__aeabi_d2lz, 38)
PLAT_STUB(__aeabi_dcmpeq, 39)
PLAT_STUB(__aeabi_dcmpge, 40)
PLAT_STUB(__aeabi_dcmpgt, 41)
PLAT_STUB(__aeabi_dcmple, 42)
PLAT_STUB(__aeabi_dcmplt, 43)
PLAT_STUB(__aeabi_dcmpun, 44)
PLAT_STUB(__aeabi_ddiv, 45)
PLAT_STUB(__aeabi_dmul, 46)
PLAT_STUB(__aeabi_dsub, 47)
PLAT_STUB(__aeabi_f2d, 48)
PLAT_STUB(__aeabi_i2d, 49)
PLAT_STUB(__aeabi_l2d, 50)
PLAT_STUB(__aeabi_ldivmod, 51)
PLAT_STUB(__aeabi_uldivmod, 52)
PLAT_STUB(__assert_func, 53)
PLAT_STUB(__cxa_thread_atexit, 54)
PLAT_STUB(__emutls_get_address, 55)
PLAT_STUB(__popcountdi2, 56)
PLAT_STUB(__popcountsi2, 57)
PLAT_STUB(__wrap_time, 58)
PLAT_STUB(abort, 59)
PLAT_STUB(acos, 60)
PLAT_STUB(aligned_alloc, 61)
PLAT_STUB(apmuSetDeepestSleepMode, 62)
PLAT_STUB(appGetECBCInfoSync, 63)
PLAT_STUB(appSetCFUN, 64)
PLAT_STUB(asin, 65)
PLAT_STUB(atan, 66)
PLAT_STUB(atan2, 67)
PLAT_STUB(calloc, 68)
PLAT_STUB(ceil, 69)
PLAT_STUB(cos, 70)
PLAT_STUB(cosh, 71)
PLAT_STUB(deregisterPSEventCallback, 72)
PLAT_STUB(exp, 73)
PLAT_STUB(fflush, 74)
PLAT_STUB(floor, 75)
PLAT_STUB(fmod, 76)
PLAT_STUB(fputc, 77)
PLAT_STUB(fputs, 78)
PLAT_STUB(free, 79)
PLAT_STUB(fwrite, 80)
PLAT_STUB(gmtime_r, 81)
PLAT_STUB(iprintf, 82)
PLAT_STUB(isspace, 83)
PLAT_STUB(localtime_r, 84)
PLAT_STUB(log, 85)
PLAT_STUB(malloc, 86)
PLAT_STUB(memchr, 87)
PLAT_STUB(memcmp, 88)
PLAT_STUB(memcpy, 89)
PLAT_STUB(memmove, 90)
PLAT_STUB(memset, 91)
PLAT_STUB(mktime, 92)
PLAT_STUB(osDelay, 93)
PLAT_STUB(osKernelGetTickCount, 94)
PLAT_STUB(pbuf_alloc, 95)
PLAT_STUB(pbuf_cat, 96)
PLAT_STUB(pbuf_free, 97)
PLAT_STUB(pbuf_ref, 98)
PLAT_STUB(pow, 99)
PLAT_STUB(psSetCdgcont, 100)
PLAT_STUB(putenv, 101)
PLAT_STUB(puts, 102)
PLAT_STUB(realloc, 103)
PLAT_STUB(registerPSEventCallback, 104)
PLAT_STUB(rngGenRandom, 105)
PLAT_STUB(round, 106)
PLAT_STUB(sin, 107)
PLAT_STUB(sinh, 108)
PLAT_STUB(siprintf, 109)
PLAT_STUB(slpManApplyPlatVoteHandle, 110)
PLAT_STUB(slpManDeepSlpTimerRegisterExpCb, 111)
PLAT_STUB(slpManDeepSlpTimerStart, 112)
PLAT_STUB(slpManPlatVoteDisableSleep, 113)
PLAT_STUB(slpManPlatVoteEnableSleep, 114)
PLAT_STUB(slpManSetPmuSleepMode, 115)
PLAT_STUB(sniprintf, 116)
PLAT_STUB(soc_power_mode, 117)
PLAT_STUB(sqrt, 118)
PLAT_STUB(strchr, 119)
PLAT_STUB(strcmp, 120)
PLAT_STUB(strcpy, 121)
PLAT_STUB(strlen, 122)
PLAT_STUB(strncmp, 123)
PLAT_STUB(strncpy, 124)
PLAT_STUB(strstr, 125)
PLAT_STUB(strtod, 126)
PLAT_STUB(tan, 127)
PLAT_STUB(tanh, 128)
PLAT_STUB(tcp_accept, 129)
PLAT_STUB(tcp_arg, 130)
PLAT_STUB(tcp_bind, 131)
PLAT_STUB(tcp_close, 132)
PLAT_STUB(tcp_connect, 133)
PLAT_STUB(tcp_err, 134)
PLAT_STUB(tcp_listen_with_backlog, 135)
PLAT_STUB(tcp_new, 136)
PLAT_STUB(tcp_output, 137)
PLAT_STUB(tcp_recv, 138)
PLAT_STUB(tcp_recved, 139)
PLAT_STUB(tcp_sent, 140)
PLAT_STUB(tcp_shutdown, 141)
PLAT_STUB(tcp_write, 142)
PLAT_STUB(tcpip_callback_with_block, 143)
PLAT_STUB(trunc, 144)
PLAT_STUB(tzset, 145)
PLAT_STUB(udp_bind, 146)
PLAT_STUB(udp_connect, 147)
PLAT_STUB(udp_new, 148)
PLAT_STUB(udp_recv, 149)
PLAT_STUB(udp_remove, 150)
PLAT_STUB(udp_send, 151)
PLAT_STUB(udp_sendto, 152)
PLAT_STUB(vPortGetHeapStats, 153)
PLAT_STUB(vPortGetHeapTag, 154)
PLAT_STUB(vPortIterateAllocations, 155)
PLAT_STUB(vPortSetHeapTag, 156)
PLAT_STUB(vQueueDelete, 157)
PLAT_STUB(vTaskDelete, 158)
PLAT_STUB(vfiprintf, 159)
PLAT_STUB(xQueueCreateMutex, 160)
PLAT_STUB(xQueueGenericCreate, 161)
PLAT_STUB(xQueueGenericReceive, 162)
PLAT_STUB(xQueueGenericSend, 163)
PLAT_STUB(xQueueGenericSendFromISR, 164)
PLAT_STUB(xQueueGetMutexHolder, 165)
PLAT_STUB(xTaskCreate, 166)
PLAT_STUB(xTaskGetCurrentTaskHandle, 167)
PLAT_STUB(xTaskNotifyWait, 168)
