// Copyright (C) 2026 Toit contributors.
// AUTO-GENERATED by tools/ec618/gen-plat-jt.toit — do not edit by hand.
//
// Per-symbol wrapper stubs + the jump-table data. Each stub is a
// 16-byte Thumb-2 sequence: load `g_plat_jt[slot]`, tail-call. The
// ABI args (r0-r3 + stack) are already in place by the time the BL
// from the caller lands, so a bare `bx` to the real function preserves
// every argument and return convention.

#include "plat_jt.h"

// Many table entries are libc/libm/compiler builtins (abort, memcpy, sin, ...).
// We declare each as `extern void *<sym>` only to take its address for the
// jump table — never to call it — so the builtin/non-function and any
// signedness mismatch is intentional and harmless. `&<sym>` still resolves to
// the real PLAT function (thumb bit intact), exactly as the old `&__real_<sym>`
// did under -Wl,--wrap.
#pragma GCC diagnostic ignored "-Wbuiltin-declaration-mismatch"

extern void *BSP_QSPI_Erase_Safe;
extern void *BSP_QSPI_Write_Safe;
extern void *BSP_SetPlatConfigItemValue;
extern void *GPIO_Config;
extern void *GPIO_IomuxEC618;
extern void *GPIO_Output;
extern void *GPIO_PullConfig;
extern void *GPIO_clearInterruptFlags;
extern void *GPIO_getInterruptFlags;
extern void *GPIO_interruptConfig;
extern void *GPIO_pinConfig;
extern void *GPIO_pinRead;
extern void *GPIO_pinWrite;
extern void *OsaSystemTimeReadRamUtc;
extern void *OsaTimerSync;
extern void *ResetStateGet;
extern void *Uart_BaseInitEx;
extern void *Uart_ChangeBR;
extern void *Uart_DeInit;
extern void *Uart_IsTSREmpty;
extern void *Uart_RxBufferClear;
extern void *Uart_RxBufferRead;
extern void *Uart_TxTaskSafe;
extern void *XIC_EnableIRQ;
extern void *XIC_SetVector;
extern void *_ZNSt13random_device7_M_finiEv;
extern void *_ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE;
extern void *_ZNSt13random_device9_M_getvalEv;
extern void *_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv;
extern void *_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_;
extern void *_ZSt25__throw_bad_function_callv;
extern void *_ZdaPv;
extern void *_ZdlPv;
extern void *__aeabi_atexit;
extern void *__aeabi_d2f;
extern void *__aeabi_d2iz;
extern void *__aeabi_d2lz;
extern void *__aeabi_dadd;
extern void *__aeabi_dcmpeq;
extern void *__aeabi_dcmpge;
extern void *__aeabi_dcmpgt;
extern void *__aeabi_dcmple;
extern void *__aeabi_dcmplt;
extern void *__aeabi_dcmpun;
extern void *__aeabi_ddiv;
extern void *__aeabi_dmul;
extern void *__aeabi_dsub;
extern void *__aeabi_f2d;
extern void *__aeabi_i2d;
extern void *__aeabi_l2d;
extern void *__aeabi_ldivmod;
extern void *__aeabi_uldivmod;
extern void *__assert_func;
extern void *__cxa_thread_atexit;
extern void *__emutls_get_address;
extern void *__popcountdi2;
extern void *__popcountsi2;
extern void *__real___wrap_time;
extern void *abort;
extern void *acos;
extern void *aligned_alloc;
extern void *apmuSetDeepestSleepMode;
extern void *appGetECBCInfoSync;
extern void *appSetCFUN;
extern void *asin;
extern void *atan;
extern void *atan2;
extern void *calloc;
extern void *ceil;
extern void *cos;
extern void *cosh;
extern void *deregisterPSEventCallback;
extern void *exp;
extern void *fclose;
extern void *feof;
extern void *fflush;
extern void *floor;
extern void *fmod;
extern void *fopen;
extern void *fotaNvmNfsPeInit;
extern void *fputc;
extern void *fputs;
extern void *fread;
extern void *free;
extern void *fseek;
extern void *fwrite;
extern void *gmtime_r;
extern void *isspace;
extern void *localtime_r;
extern void *log;
extern void *malloc;
extern void *memchr;
extern void *memcmp;
extern void *memcpy;
extern void *memmove;
extern void *memset;
extern void *mktime;
extern void *osDelay;
extern void *osKernelGetTickCount;
extern void *pbuf_alloc;
extern void *pbuf_cat;
extern void *pbuf_free;
extern void *pbuf_ref;
extern void *pow;
extern void *printf;
extern void *psSetCdgcont;
extern void *putchar;
extern void *putenv;
extern void *puts;
extern void *realloc;
extern void *registerPSEventCallback;
extern void *rngGenRandom;
extern void *round;
extern void *sin;
extern void *sinh;
extern void *slot_marker_read;
extern void *slot_marker_write;
extern void *slpManApplyPlatVoteHandle;
extern void *slpManDeepSlpTimerRegisterExpCb;
extern void *slpManDeepSlpTimerStart;
extern void *slpManPlatVoteDisableSleep;
extern void *slpManPlatVoteEnableSleep;
extern void *slpManSetPmuSleepMode;
extern void *snprintf;
extern void *soc_power_mode;
extern void *sprintf;
extern void *sqrt;
extern void *strchr;
extern void *strcmp;
extern void *strcpy;
extern void *strdup;
extern void *strerror;
extern void *strlen;
extern void *strncmp;
extern void *strncpy;
extern void *strnlen;
extern void *strstr;
extern void *strtod;
extern void *tan;
extern void *tanh;
extern void *tcp_accept;
extern void *tcp_arg;
extern void *tcp_bind;
extern void *tcp_close;
extern void *tcp_connect;
extern void *tcp_err;
extern void *tcp_listen_with_backlog;
extern void *tcp_new;
extern void *tcp_output;
extern void *tcp_recv;
extern void *tcp_recved;
extern void *tcp_sent;
extern void *tcp_shutdown;
extern void *tcp_write;
extern void *tcpip_callback_with_block;
extern void *trunc;
extern void *tzset;
extern void *udp_bind;
extern void *udp_connect;
extern void *udp_new;
extern void *udp_recv;
extern void *udp_remove;
extern void *udp_send;
extern void *udp_sendto;
extern void *vPortGetHeapStats;
extern void *vPortGetHeapTag;
extern void *vPortIterateAllocations;
extern void *vPortSetHeapTag;
extern void *vQueueDelete;
extern void *vTaskDelete;
extern void *vfprintf;
extern void *xQueueCreateMutex;
extern void *xQueueGenericCreate;
extern void *xQueueGenericReceive;
extern void *xQueueGenericSend;
extern void *xQueueGenericSendFromISR;
extern void *xQueueGetMutexHolder;
extern void *xTaskCreate;
extern void *xTaskGenericNotify;
extern void *xTaskGetCurrentTaskHandle;
extern void *xTaskNotifyWait;

// Placed at a fixed flash address (see ec618_0h00_flash.c, .jt_data
// section) so dual-linked VM slots resolve to the same g_plat_jt[]
// regardless of which slot's image they were linked from.
__attribute__((section(".jt_data"), used))
void *const g_plat_jt[PLAT_JT_COUNT] = {
    [PLAT_JT_BSP_QSPI_Erase_Safe] = &BSP_QSPI_Erase_Safe,
    [PLAT_JT_BSP_QSPI_Write_Safe] = &BSP_QSPI_Write_Safe,
    [PLAT_JT_BSP_SetPlatConfigItemValue] = &BSP_SetPlatConfigItemValue,
    [PLAT_JT_GPIO_Config] = &GPIO_Config,
    [PLAT_JT_GPIO_IomuxEC618] = &GPIO_IomuxEC618,
    [PLAT_JT_GPIO_Output] = &GPIO_Output,
    [PLAT_JT_GPIO_PullConfig] = &GPIO_PullConfig,
    [PLAT_JT_GPIO_clearInterruptFlags] = &GPIO_clearInterruptFlags,
    [PLAT_JT_GPIO_getInterruptFlags] = &GPIO_getInterruptFlags,
    [PLAT_JT_GPIO_interruptConfig] = &GPIO_interruptConfig,
    [PLAT_JT_GPIO_pinConfig] = &GPIO_pinConfig,
    [PLAT_JT_GPIO_pinRead] = &GPIO_pinRead,
    [PLAT_JT_GPIO_pinWrite] = &GPIO_pinWrite,
    [PLAT_JT_OsaSystemTimeReadRamUtc] = &OsaSystemTimeReadRamUtc,
    [PLAT_JT_OsaTimerSync] = &OsaTimerSync,
    [PLAT_JT_ResetStateGet] = &ResetStateGet,
    [PLAT_JT_Uart_BaseInitEx] = &Uart_BaseInitEx,
    [PLAT_JT_Uart_ChangeBR] = &Uart_ChangeBR,
    [PLAT_JT_Uart_DeInit] = &Uart_DeInit,
    [PLAT_JT_Uart_IsTSREmpty] = &Uart_IsTSREmpty,
    [PLAT_JT_Uart_RxBufferClear] = &Uart_RxBufferClear,
    [PLAT_JT_Uart_RxBufferRead] = &Uart_RxBufferRead,
    [PLAT_JT_Uart_TxTaskSafe] = &Uart_TxTaskSafe,
    [PLAT_JT_XIC_EnableIRQ] = &XIC_EnableIRQ,
    [PLAT_JT_XIC_SetVector] = &XIC_SetVector,
    [PLAT_JT__ZNSt13random_device7_M_finiEv] = &_ZNSt13random_device7_M_finiEv,
    [PLAT_JT__ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE] = &_ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE,
    [PLAT_JT__ZNSt13random_device9_M_getvalEv] = &_ZNSt13random_device9_M_getvalEv,
    [PLAT_JT__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv] = &_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv,
    [PLAT_JT__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_] = &_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_,
    [PLAT_JT__ZSt25__throw_bad_function_callv] = &_ZSt25__throw_bad_function_callv,
    [PLAT_JT__ZdaPv] = &_ZdaPv,
    [PLAT_JT__ZdlPv] = &_ZdlPv,
    [PLAT_JT___aeabi_atexit] = &__aeabi_atexit,
    [PLAT_JT___aeabi_d2f] = &__aeabi_d2f,
    [PLAT_JT___aeabi_d2iz] = &__aeabi_d2iz,
    [PLAT_JT___aeabi_d2lz] = &__aeabi_d2lz,
    [PLAT_JT___aeabi_dadd] = &__aeabi_dadd,
    [PLAT_JT___aeabi_dcmpeq] = &__aeabi_dcmpeq,
    [PLAT_JT___aeabi_dcmpge] = &__aeabi_dcmpge,
    [PLAT_JT___aeabi_dcmpgt] = &__aeabi_dcmpgt,
    [PLAT_JT___aeabi_dcmple] = &__aeabi_dcmple,
    [PLAT_JT___aeabi_dcmplt] = &__aeabi_dcmplt,
    [PLAT_JT___aeabi_dcmpun] = &__aeabi_dcmpun,
    [PLAT_JT___aeabi_ddiv] = &__aeabi_ddiv,
    [PLAT_JT___aeabi_dmul] = &__aeabi_dmul,
    [PLAT_JT___aeabi_dsub] = &__aeabi_dsub,
    [PLAT_JT___aeabi_f2d] = &__aeabi_f2d,
    [PLAT_JT___aeabi_i2d] = &__aeabi_i2d,
    [PLAT_JT___aeabi_l2d] = &__aeabi_l2d,
    [PLAT_JT___aeabi_ldivmod] = &__aeabi_ldivmod,
    [PLAT_JT___aeabi_uldivmod] = &__aeabi_uldivmod,
    [PLAT_JT___assert_func] = &__assert_func,
    [PLAT_JT___cxa_thread_atexit] = &__cxa_thread_atexit,
    [PLAT_JT___emutls_get_address] = &__emutls_get_address,
    [PLAT_JT___popcountdi2] = &__popcountdi2,
    [PLAT_JT___popcountsi2] = &__popcountsi2,
    [PLAT_JT___wrap_time] = &__real___wrap_time,
    [PLAT_JT_abort] = &abort,
    [PLAT_JT_acos] = &acos,
    [PLAT_JT_aligned_alloc] = &aligned_alloc,
    [PLAT_JT_apmuSetDeepestSleepMode] = &apmuSetDeepestSleepMode,
    [PLAT_JT_appGetECBCInfoSync] = &appGetECBCInfoSync,
    [PLAT_JT_appSetCFUN] = &appSetCFUN,
    [PLAT_JT_asin] = &asin,
    [PLAT_JT_atan] = &atan,
    [PLAT_JT_atan2] = &atan2,
    [PLAT_JT_calloc] = &calloc,
    [PLAT_JT_ceil] = &ceil,
    [PLAT_JT_cos] = &cos,
    [PLAT_JT_cosh] = &cosh,
    [PLAT_JT_deregisterPSEventCallback] = &deregisterPSEventCallback,
    [PLAT_JT_exp] = &exp,
    [PLAT_JT_fclose] = &fclose,
    [PLAT_JT_feof] = &feof,
    [PLAT_JT_fflush] = &fflush,
    [PLAT_JT_floor] = &floor,
    [PLAT_JT_fmod] = &fmod,
    [PLAT_JT_fopen] = &fopen,
    [PLAT_JT_fotaNvmNfsPeInit] = &fotaNvmNfsPeInit,
    [PLAT_JT_fputc] = &fputc,
    [PLAT_JT_fputs] = &fputs,
    [PLAT_JT_fread] = &fread,
    [PLAT_JT_free] = &free,
    [PLAT_JT_fseek] = &fseek,
    [PLAT_JT_fwrite] = &fwrite,
    [PLAT_JT_gmtime_r] = &gmtime_r,
    [PLAT_JT_isspace] = &isspace,
    [PLAT_JT_localtime_r] = &localtime_r,
    [PLAT_JT_log] = &log,
    [PLAT_JT_malloc] = &malloc,
    [PLAT_JT_memchr] = &memchr,
    [PLAT_JT_memcmp] = &memcmp,
    [PLAT_JT_memcpy] = &memcpy,
    [PLAT_JT_memmove] = &memmove,
    [PLAT_JT_memset] = &memset,
    [PLAT_JT_mktime] = &mktime,
    [PLAT_JT_osDelay] = &osDelay,
    [PLAT_JT_osKernelGetTickCount] = &osKernelGetTickCount,
    [PLAT_JT_pbuf_alloc] = &pbuf_alloc,
    [PLAT_JT_pbuf_cat] = &pbuf_cat,
    [PLAT_JT_pbuf_free] = &pbuf_free,
    [PLAT_JT_pbuf_ref] = &pbuf_ref,
    [PLAT_JT_pow] = &pow,
    [PLAT_JT_printf] = &printf,
    [PLAT_JT_psSetCdgcont] = &psSetCdgcont,
    [PLAT_JT_putchar] = &putchar,
    [PLAT_JT_putenv] = &putenv,
    [PLAT_JT_puts] = &puts,
    [PLAT_JT_realloc] = &realloc,
    [PLAT_JT_registerPSEventCallback] = &registerPSEventCallback,
    [PLAT_JT_rngGenRandom] = &rngGenRandom,
    [PLAT_JT_round] = &round,
    [PLAT_JT_sin] = &sin,
    [PLAT_JT_sinh] = &sinh,
    [PLAT_JT_slot_marker_read] = &slot_marker_read,
    [PLAT_JT_slot_marker_write] = &slot_marker_write,
    [PLAT_JT_slpManApplyPlatVoteHandle] = &slpManApplyPlatVoteHandle,
    [PLAT_JT_slpManDeepSlpTimerRegisterExpCb] = &slpManDeepSlpTimerRegisterExpCb,
    [PLAT_JT_slpManDeepSlpTimerStart] = &slpManDeepSlpTimerStart,
    [PLAT_JT_slpManPlatVoteDisableSleep] = &slpManPlatVoteDisableSleep,
    [PLAT_JT_slpManPlatVoteEnableSleep] = &slpManPlatVoteEnableSleep,
    [PLAT_JT_slpManSetPmuSleepMode] = &slpManSetPmuSleepMode,
    [PLAT_JT_snprintf] = &snprintf,
    [PLAT_JT_soc_power_mode] = &soc_power_mode,
    [PLAT_JT_sprintf] = &sprintf,
    [PLAT_JT_sqrt] = &sqrt,
    [PLAT_JT_strchr] = &strchr,
    [PLAT_JT_strcmp] = &strcmp,
    [PLAT_JT_strcpy] = &strcpy,
    [PLAT_JT_strdup] = &strdup,
    [PLAT_JT_strerror] = &strerror,
    [PLAT_JT_strlen] = &strlen,
    [PLAT_JT_strncmp] = &strncmp,
    [PLAT_JT_strncpy] = &strncpy,
    [PLAT_JT_strnlen] = &strnlen,
    [PLAT_JT_strstr] = &strstr,
    [PLAT_JT_strtod] = &strtod,
    [PLAT_JT_tan] = &tan,
    [PLAT_JT_tanh] = &tanh,
    [PLAT_JT_tcp_accept] = &tcp_accept,
    [PLAT_JT_tcp_arg] = &tcp_arg,
    [PLAT_JT_tcp_bind] = &tcp_bind,
    [PLAT_JT_tcp_close] = &tcp_close,
    [PLAT_JT_tcp_connect] = &tcp_connect,
    [PLAT_JT_tcp_err] = &tcp_err,
    [PLAT_JT_tcp_listen_with_backlog] = &tcp_listen_with_backlog,
    [PLAT_JT_tcp_new] = &tcp_new,
    [PLAT_JT_tcp_output] = &tcp_output,
    [PLAT_JT_tcp_recv] = &tcp_recv,
    [PLAT_JT_tcp_recved] = &tcp_recved,
    [PLAT_JT_tcp_sent] = &tcp_sent,
    [PLAT_JT_tcp_shutdown] = &tcp_shutdown,
    [PLAT_JT_tcp_write] = &tcp_write,
    [PLAT_JT_tcpip_callback_with_block] = &tcpip_callback_with_block,
    [PLAT_JT_trunc] = &trunc,
    [PLAT_JT_tzset] = &tzset,
    [PLAT_JT_udp_bind] = &udp_bind,
    [PLAT_JT_udp_connect] = &udp_connect,
    [PLAT_JT_udp_new] = &udp_new,
    [PLAT_JT_udp_recv] = &udp_recv,
    [PLAT_JT_udp_remove] = &udp_remove,
    [PLAT_JT_udp_send] = &udp_send,
    [PLAT_JT_udp_sendto] = &udp_sendto,
    [PLAT_JT_vPortGetHeapStats] = &vPortGetHeapStats,
    [PLAT_JT_vPortGetHeapTag] = &vPortGetHeapTag,
    [PLAT_JT_vPortIterateAllocations] = &vPortIterateAllocations,
    [PLAT_JT_vPortSetHeapTag] = &vPortSetHeapTag,
    [PLAT_JT_vQueueDelete] = &vQueueDelete,
    [PLAT_JT_vTaskDelete] = &vTaskDelete,
    [PLAT_JT_vfprintf] = &vfprintf,
    [PLAT_JT_xQueueCreateMutex] = &xQueueCreateMutex,
    [PLAT_JT_xQueueGenericCreate] = &xQueueGenericCreate,
    [PLAT_JT_xQueueGenericReceive] = &xQueueGenericReceive,
    [PLAT_JT_xQueueGenericSend] = &xQueueGenericSend,
    [PLAT_JT_xQueueGenericSendFromISR] = &xQueueGenericSendFromISR,
    [PLAT_JT_xQueueGetMutexHolder] = &xQueueGetMutexHolder,
    [PLAT_JT_xTaskCreate] = &xTaskCreate,
    [PLAT_JT_xTaskGenericNotify] = &xTaskGenericNotify,
    [PLAT_JT_xTaskGetCurrentTaskHandle] = &xTaskGetCurrentTaskHandle,
    [PLAT_JT_xTaskNotifyWait] = &xTaskNotifyWait,
};

#define PLAT_STUB(name, slot)                                       \
    __attribute__((naked, noinline))                                 \
    void __wrap_##name(void) {                                      \
        __asm__ volatile (                                           \
            "movw r12, #:lower16:g_plat_jt + " #slot " * 4 \n"      \
            "movt r12, #:upper16:g_plat_jt + " #slot " * 4 \n"      \
            "ldr  r12, [r12]                              \n"       \
            "bx   r12                                     \n"       \
        );                                                           \
    }

PLAT_STUB(BSP_QSPI_Erase_Safe, 0)
PLAT_STUB(BSP_QSPI_Write_Safe, 1)
PLAT_STUB(BSP_SetPlatConfigItemValue, 2)
PLAT_STUB(GPIO_Config, 3)
PLAT_STUB(GPIO_IomuxEC618, 4)
PLAT_STUB(GPIO_Output, 5)
PLAT_STUB(GPIO_PullConfig, 6)
PLAT_STUB(GPIO_clearInterruptFlags, 7)
PLAT_STUB(GPIO_getInterruptFlags, 8)
PLAT_STUB(GPIO_interruptConfig, 9)
PLAT_STUB(GPIO_pinConfig, 10)
PLAT_STUB(GPIO_pinRead, 11)
PLAT_STUB(GPIO_pinWrite, 12)
PLAT_STUB(OsaSystemTimeReadRamUtc, 13)
PLAT_STUB(OsaTimerSync, 14)
PLAT_STUB(ResetStateGet, 15)
PLAT_STUB(Uart_BaseInitEx, 16)
PLAT_STUB(Uart_ChangeBR, 17)
PLAT_STUB(Uart_DeInit, 18)
PLAT_STUB(Uart_IsTSREmpty, 19)
PLAT_STUB(Uart_RxBufferClear, 20)
PLAT_STUB(Uart_RxBufferRead, 21)
PLAT_STUB(Uart_TxTaskSafe, 22)
PLAT_STUB(XIC_EnableIRQ, 23)
PLAT_STUB(XIC_SetVector, 24)
PLAT_STUB(_ZNSt13random_device7_M_finiEv, 25)
PLAT_STUB(_ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE, 26)
PLAT_STUB(_ZNSt13random_device9_M_getvalEv, 27)
PLAT_STUB(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv, 28)
PLAT_STUB(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_, 29)
PLAT_STUB(_ZSt25__throw_bad_function_callv, 30)
PLAT_STUB(_ZdaPv, 31)
PLAT_STUB(_ZdlPv, 32)
PLAT_STUB(__aeabi_atexit, 33)
PLAT_STUB(__aeabi_d2f, 34)
PLAT_STUB(__aeabi_d2iz, 35)
PLAT_STUB(__aeabi_d2lz, 36)
PLAT_STUB(__aeabi_dadd, 37)
PLAT_STUB(__aeabi_dcmpeq, 38)
PLAT_STUB(__aeabi_dcmpge, 39)
PLAT_STUB(__aeabi_dcmpgt, 40)
PLAT_STUB(__aeabi_dcmple, 41)
PLAT_STUB(__aeabi_dcmplt, 42)
PLAT_STUB(__aeabi_dcmpun, 43)
PLAT_STUB(__aeabi_ddiv, 44)
PLAT_STUB(__aeabi_dmul, 45)
PLAT_STUB(__aeabi_dsub, 46)
PLAT_STUB(__aeabi_f2d, 47)
PLAT_STUB(__aeabi_i2d, 48)
PLAT_STUB(__aeabi_l2d, 49)
PLAT_STUB(__aeabi_ldivmod, 50)
PLAT_STUB(__aeabi_uldivmod, 51)
PLAT_STUB(__assert_func, 52)
PLAT_STUB(__cxa_thread_atexit, 53)
PLAT_STUB(__emutls_get_address, 54)
PLAT_STUB(__popcountdi2, 55)
PLAT_STUB(__popcountsi2, 56)
PLAT_STUB(__wrap_time, 57)
PLAT_STUB(abort, 58)
PLAT_STUB(acos, 59)
PLAT_STUB(aligned_alloc, 60)
PLAT_STUB(apmuSetDeepestSleepMode, 61)
PLAT_STUB(appGetECBCInfoSync, 62)
PLAT_STUB(appSetCFUN, 63)
PLAT_STUB(asin, 64)
PLAT_STUB(atan, 65)
PLAT_STUB(atan2, 66)
PLAT_STUB(calloc, 67)
PLAT_STUB(ceil, 68)
PLAT_STUB(cos, 69)
PLAT_STUB(cosh, 70)
PLAT_STUB(deregisterPSEventCallback, 71)
PLAT_STUB(exp, 72)
PLAT_STUB(fclose, 73)
PLAT_STUB(feof, 74)
PLAT_STUB(fflush, 75)
PLAT_STUB(floor, 76)
PLAT_STUB(fmod, 77)
PLAT_STUB(fopen, 78)
PLAT_STUB(fotaNvmNfsPeInit, 79)
PLAT_STUB(fputc, 80)
PLAT_STUB(fputs, 81)
PLAT_STUB(fread, 82)
PLAT_STUB(free, 83)
PLAT_STUB(fseek, 84)
PLAT_STUB(fwrite, 85)
PLAT_STUB(gmtime_r, 86)
PLAT_STUB(isspace, 87)
PLAT_STUB(localtime_r, 88)
PLAT_STUB(log, 89)
PLAT_STUB(malloc, 90)
PLAT_STUB(memchr, 91)
PLAT_STUB(memcmp, 92)
PLAT_STUB(memcpy, 93)
PLAT_STUB(memmove, 94)
PLAT_STUB(memset, 95)
PLAT_STUB(mktime, 96)
PLAT_STUB(osDelay, 97)
PLAT_STUB(osKernelGetTickCount, 98)
PLAT_STUB(pbuf_alloc, 99)
PLAT_STUB(pbuf_cat, 100)
PLAT_STUB(pbuf_free, 101)
PLAT_STUB(pbuf_ref, 102)
PLAT_STUB(pow, 103)
PLAT_STUB(printf, 104)
PLAT_STUB(psSetCdgcont, 105)
PLAT_STUB(putchar, 106)
PLAT_STUB(putenv, 107)
PLAT_STUB(puts, 108)
PLAT_STUB(realloc, 109)
PLAT_STUB(registerPSEventCallback, 110)
PLAT_STUB(rngGenRandom, 111)
PLAT_STUB(round, 112)
PLAT_STUB(sin, 113)
PLAT_STUB(sinh, 114)
PLAT_STUB(slot_marker_read, 115)
PLAT_STUB(slot_marker_write, 116)
PLAT_STUB(slpManApplyPlatVoteHandle, 117)
PLAT_STUB(slpManDeepSlpTimerRegisterExpCb, 118)
PLAT_STUB(slpManDeepSlpTimerStart, 119)
PLAT_STUB(slpManPlatVoteDisableSleep, 120)
PLAT_STUB(slpManPlatVoteEnableSleep, 121)
PLAT_STUB(slpManSetPmuSleepMode, 122)
PLAT_STUB(snprintf, 123)
PLAT_STUB(soc_power_mode, 124)
PLAT_STUB(sprintf, 125)
PLAT_STUB(sqrt, 126)
PLAT_STUB(strchr, 127)
PLAT_STUB(strcmp, 128)
PLAT_STUB(strcpy, 129)
PLAT_STUB(strdup, 130)
PLAT_STUB(strerror, 131)
PLAT_STUB(strlen, 132)
PLAT_STUB(strncmp, 133)
PLAT_STUB(strncpy, 134)
PLAT_STUB(strnlen, 135)
PLAT_STUB(strstr, 136)
PLAT_STUB(strtod, 137)
PLAT_STUB(tan, 138)
PLAT_STUB(tanh, 139)
PLAT_STUB(tcp_accept, 140)
PLAT_STUB(tcp_arg, 141)
PLAT_STUB(tcp_bind, 142)
PLAT_STUB(tcp_close, 143)
PLAT_STUB(tcp_connect, 144)
PLAT_STUB(tcp_err, 145)
PLAT_STUB(tcp_listen_with_backlog, 146)
PLAT_STUB(tcp_new, 147)
PLAT_STUB(tcp_output, 148)
PLAT_STUB(tcp_recv, 149)
PLAT_STUB(tcp_recved, 150)
PLAT_STUB(tcp_sent, 151)
PLAT_STUB(tcp_shutdown, 152)
PLAT_STUB(tcp_write, 153)
PLAT_STUB(tcpip_callback_with_block, 154)
PLAT_STUB(trunc, 155)
PLAT_STUB(tzset, 156)
PLAT_STUB(udp_bind, 157)
PLAT_STUB(udp_connect, 158)
PLAT_STUB(udp_new, 159)
PLAT_STUB(udp_recv, 160)
PLAT_STUB(udp_remove, 161)
PLAT_STUB(udp_send, 162)
PLAT_STUB(udp_sendto, 163)
PLAT_STUB(vPortGetHeapStats, 164)
PLAT_STUB(vPortGetHeapTag, 165)
PLAT_STUB(vPortIterateAllocations, 166)
PLAT_STUB(vPortSetHeapTag, 167)
PLAT_STUB(vQueueDelete, 168)
PLAT_STUB(vTaskDelete, 169)
PLAT_STUB(vfprintf, 170)
PLAT_STUB(xQueueCreateMutex, 171)
PLAT_STUB(xQueueGenericCreate, 172)
PLAT_STUB(xQueueGenericReceive, 173)
PLAT_STUB(xQueueGenericSend, 174)
PLAT_STUB(xQueueGenericSendFromISR, 175)
PLAT_STUB(xQueueGetMutexHolder, 176)
PLAT_STUB(xTaskCreate, 177)
PLAT_STUB(xTaskGenericNotify, 178)
PLAT_STUB(xTaskGetCurrentTaskHandle, 179)
PLAT_STUB(xTaskNotifyWait, 180)
